name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_deployment_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r api/requirements.txt
      - name: Test with pytest
        run: |
          pytest
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY}}
          heroku_app_name: "apiscoringloan-tomatoketchoup" #Must be unique in Heroku
          heroku_email: "anne.desmedt@gmx.fr"
          appdir: 'api'
          buildpack: heroku/pyhon
          dontuseforce: 0
        env:
          PYTHON_RUNTIME_VERSION: 3.8.12
  build_deployment_dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY}}
          heroku_app_name: "dashscoringloan-tomatoketchoup" #Must be unique in Heroku
          heroku_email: "anne.desmedt@gmx.fr"
          appdir: 'dashboard'
          buildpack: heroku/python
          dontuseforce: 0
        env:
          PYTHON_RUNTIME_VERSION: 3.8.12
